// Generated from Rotozoomer_shared_defs.py.
// Shared constants for the Rotozoomer OCS build.

#define HAM_COLUMNS                                      56
#define HAM_ROWS                                         52
#define HAM_PIXEL_SIZE                                   4
#define HAM_FRAME_COUNT                                  256
#define HAM_FRAME_PARAM_BYTES                            12
#define HAM_LIVE_ROWS                                    2
#define HAM_TEMPORAL_START_ROW                           2
#define HAM_TEMPORAL_HALF_ROWS                           8
#define HAM_TEMPORAL_LOWER_START_ROW                     10
#define HAM_HALFRATE_START_ROW                           18
#define HAM_DYNAMIC_PLANE_BYTES                          504
#define HAM_DYNAMIC_BITMAP_BYTES                         2016
#define HAM_HALFRATE_ROWS                                34
#define HAM_HALFRATE_ROW_CACHE_PLANE_BYTES               952
#define HAM_HALFRATE_ROW_CACHE_FRAME_BYTES               3808
#define HAM_HALFRATE_ROW_CACHE_BYTES                     487424
#define HAM_TEMPORAL_UPPER_DEST_OFFSET                   56
#define HAM_TEMPORAL_LOWER_DEST_OFFSET                   280
#define HAM_COPPER_PTR_PLANES                            4
#define HAM_DISPLAY_BPU                                  7
#define HAM_COPPER_BPLPTR_WORD                           23
#define HAM_COPPER_TEMPORAL_UPPER_BPLPTR_WORD            53
#define HAM_COPPER_TEMPORAL_LOWER_BPLPTR_WORD            155
#define HAM_COPPER_HALFRATE_BPLPTR_WORD                  257
#define HAM_COPPER_HALFRATE_BPLPTR_BYTES                 514
#define HAM_COPPER_BYTES                                 1344
#define HAM_CHIP_BLOCK_BYTES                             6720
#define HAM_HALF_COLUMNS                                 28
#define HAM_HALF_ROWS                                    26
#define HAM_VPOS_START                                   0x0044
#define HAM_DIWSTRT                                      0x4481
#define HAM_DIWSTOP                                      0x14C1
#define HAM_DDFSTRT                                      0x0050
#define HAM_DDFSTOP                                      0x00B8
#define HAM_REPEAT_MOD                                   0xFFE4
#define HAM_ADVANCE_MOD                                  0
#define HAM_CONTROL_WORD_P5                              0x3333
#define HAM_CONTROL_WORD_P6                              0x6666
#define HAM_CORE_DONE_LOW                                0x4C
#define HAM_TEMPORAL_UPPER_DONE_LOW                      0x6C
#define HAM_TEMPORAL_DONE_LOW                            0x8C
#define HAM_ZOOM_BASE                                    256
#define HAM_ZOOM_AMPLITUDE                               96
#define HAM_ANGLE_PHASE_STEP                             1
#define HAM_CENTER_U                                     0x4000
#define HAM_CENTER_V                                     0x4000
