// Generated from Rotozoomer_shared_defs.py.
// Shared constants for Rotozoomer.c and Rotozoomer_vasm.s.

#define HAM_COLUMNS                              56
#define HAM_ROWS                                 52
#define HAM_PIXEL_SIZE                           4
#define HAM_DISPLAY_WIDTH                        224
#define HAM_DISPLAY_HEIGHT                       208
#define HAM_FETCH_BYTES                          28
#define HAM_PLANE_BYTES                          1456
#define HAM_FRAME_COUNT                          256
#define HAM_LIVE_ROWS                            2
#define HAM_TEMPORAL_START_ROW                   2
#define HAM_TEMPORAL_ROWS                        26
#define HAM_TEMPORAL_HALF_ROWS                   13
#define HAM_HALFRATE_START_ROW                   28
#define HAM_SLOW_START_ROW                       49
#define HAM_CACHE_START_ROW                      52
#define HAM_SLOW_ROWS                            3
#define HAM_CACHE_ROWS                           0
#define HAM_DYNAMIC_ROWS                         28
#define HAM_DYNAMIC_PLANE_BYTES                  784
#define HAM_DYNAMIC_BITMAP_BYTES                 3136
#define HAM_ROW_CACHE_PLANE_BYTES                0
#define HAM_ROW_CACHE_FRAME_BYTES                0
#define HAM_ROW_CACHE_BYTES                      0
#define HAM_TEMPORAL_ROW_BYTES                   728
#define HAM_HALFRATE_ROWS                        21
#define HAM_HALFRATE_FRAME_COUNT                 128
#define HAM_HALFRATE_PLANE_BYTES                 588
#define HAM_HALFRATE_ROW_CACHE_PLANE_BYTES       588
#define HAM_HALFRATE_ROW_CACHE_FRAME_BYTES       2352
#define HAM_HALFRATE_ROW_CACHE_BYTES             301056
#define HAM_HALFRATE_POINTER_WORDS               8
#define HAM_HALFRATE_POINTER_FRAME_BYTES         16
#define HAM_HALFRATE_POINTER_BYTES               2048
#define HAM_SLOW_PLANE_BYTES                     84
#define HAM_SLOW_ROW_CACHE_PLANE_BYTES           84
#define HAM_SLOW_ROW_CACHE_FRAME_BYTES           336
#define HAM_SLOW_ROW_CACHE_BYTES                 86016
#define HAM_DYNAMIC_BUFFER_BYTES                 6272
#define HAM_TEMPORAL_UPPER_DEST_OFFSET           56
#define HAM_TEMPORAL_LOWER_DEST_OFFSET           420
#define HAM_COPPER_BPLPTR_WORD                   23
#define HAM_COPPER_HALFRATE_BPLPTR_WORD          397
#define HAM_COPPER_HALFRATE_BPLPTR_BYTES         794
#define HAM_COPPER_SLOW_BPLPTR_WORD              657
#define HAM_COPPER_SLOW_BPLPTR_BYTES             1314
#define HAM_COPPER_CACHE_BPLPTR_WORD             0
#define HAM_COPPER_CACHE_BPLPTR_BYTES            0
#define HAM_COPPER_WORDS                         698
#define HAM_COPPER_BYTES                         1396
#define HAM_CHIP_BLOCK_BYTES                     9064
#define HAM_TOTAL_CHIP_BYTES                     396136
#define HAM_HALF_COLUMNS                         28
#define HAM_HALF_ROWS                            26
#define HAM_SCREEN_WIDTH                         320
#define HAM_SCREEN_HEIGHT                        256
#define HAM_START_X                              48
#define HAM_PAL_VPOS_TOP                         0x002C
#define HAM_VPOS_START                           0x0044
#define HAM_VPOS_STOP                            0x0114
#define HAM_COPPER_WRAP_ROW                      47
#define HAM_DIWSTRT                              0x4481
#define HAM_DIWSTOP                              0x14C1
#define HAM_DDF_SHIFT_BYTES                      6
#define HAM_DDFSTRT                              0x0050
#define HAM_DDFSTOP                              0x00B8
#define HAM_REPEAT_MOD                           0xFFE4
#define HAM_ADVANCE_MOD                          0
#define HAM_DISPLAY_BPU                          7
#define HAM_CONTROL_WORD_P5                      0x3333
#define HAM_CONTROL_WORD_P6                      0x6666
#define HAM_CORE_DONE_LOW                        0x4C
#define HAM_TEMPORAL_UPPER_DONE_LOW              0x80
#define HAM_TEMPORAL_DONE_LOW                    0xB4
#define HAM_SLOW_DONE_LOW                        0x14
#define HAM_ZOOM_BASE                            256
#define HAM_ZOOM_AMPLITUDE                       96
#define HAM_ANGLE_PHASE_STEP                     2
#define HAM_CENTER_U                             0x4000
#define HAM_CENTER_V                             0x4000
#define BLTPRI_SET                               0x8400
#define BLTPRI_CLR                               0x0400
#define BLIT_TEMPORAL_WIDE_SIZE                  0x0100
#define BLIT_TEMPORAL_TAIL_SIZE                  0x0136
#define BLIT_TEMPORAL_WIDE_BYTES                 128
#define BLIT_TEMPORAL_TAIL_BYTES                 108
#define BLIT_TEMPORAL_WIDE_MOD                   656
#define BLIT_TEMPORAL_TAIL_MOD                   676
#define BLIT_TEMPORAL_WIDE_MOD_LONG              0x02900290
#define BLIT_TEMPORAL_TAIL_MOD_LONG              0x02A402A4
