// Generated from Rotozoomer_shared_defs.py.
// Shared constants for the Rotozoomer AGA build.

#define HAM_COLUMNS                                      56
#define HAM_ROWS                                         52
#define HAM_PIXEL_SIZE                                   4
#define HAM_FRAME_COUNT                                  256
#define HAM_FRAME_PARAM_BYTES                            12
#define HAM_LIVE_ROWS                                    2
#define HAM_TEMPORAL_START_ROW                           2
#define HAM_TEMPORAL_HALF_ROWS                           8
#define HAM_TEMPORAL_LOWER_START_ROW                     10
#define HAM_HALFRATE_START_ROW                           18
#define HAM_DYNAMIC_PLANE_BYTES                          504
#define HAM_DYNAMIC_BITMAP_BYTES                         2016
#define HAM_HALFRATE_ROWS                                34
#define HAM_HALFRATE_ROW_CACHE_PLANE_BYTES               952
#define HAM_HALFRATE_ROW_CACHE_FRAME_BYTES               3808
#define HAM_HALFRATE_ROW_CACHE_BYTES                     487424
#define HAM_TEMPORAL_UPPER_DEST_OFFSET                   56
#define HAM_TEMPORAL_LOWER_DEST_OFFSET                   280
#define HAM_COPPER_PTR_PLANES                            6
#define HAM_DISPLAY_BPU                                  6
#define HAM_AGA_CONTROL_PLANE_BYTES                      1456
#define HAM_AGA_CONTROL_PLANES_BYTES                     2912
#define HAM_AGA_BPLCON3_RESET                            0x0000
#define HAM_AGA_BPLCON4_RESET                            0x0000
#define HAM_AGA_FMODE_RESET                              0x0000
#define HAM_AGA_BPLCON3_LOCT                             0x0200
#define HAM_COPPER_BPLPTR_WORD                           25
#define HAM_COPPER_TEMPORAL_UPPER_BPLPTR_WORD            63
#define HAM_COPPER_TEMPORAL_LOWER_BPLPTR_WORD            173
#define HAM_COPPER_HALFRATE_BPLPTR_WORD                  283
#define HAM_COPPER_HALFRATE_BPLPTR_BYTES                 566
#define HAM_COPPER_BYTES                                 1412
#define HAM_CHIP_BLOCK_BYTES                             6856
#define HAM_HALF_COLUMNS                                 28
#define HAM_HALF_ROWS                                    26
#define HAM_VPOS_START                                   0x0044
#define HAM_DIWSTRT                                      0x4481
#define HAM_DIWSTOP                                      0x14C1
#define HAM_DDFSTRT                                      0x0050
#define HAM_DDFSTOP                                      0x00B8
#define HAM_REPEAT_MOD                                   0xFFE4
#define HAM_ADVANCE_MOD                                  0
#define HAM_CONTROL_PLANE5_WORD                          0x3333
#define HAM_CONTROL_PLANE6_WORD                          0x6666
#define HAM_CORE_DONE_LOW                                0x4C
#define HAM_TEMPORAL_UPPER_DONE_LOW                      0x6C
#define HAM_TEMPORAL_DONE_LOW                            0x8C
#define HAM_ZOOM_BASE                                    256
#define HAM_ZOOM_AMPLITUDE                               96
#define HAM_ANGLE_PHASE_STEP                             1
#define HAM_CENTER_U                                     0x4000
#define HAM_CENTER_V                                     0x4000
