// Generated from Rotozoomer_shared_defs.py.
// Shared constants for Rotozoomer.c and Rotozoomer_vasm.s.

#define HAM_COLUMNS                              56
#define HAM_ROWS                                 52
#define HAM_PIXEL_SIZE                           4
#define HAM_DISPLAY_WIDTH                        224
#define HAM_DISPLAY_HEIGHT                       208
#define HAM_FETCH_BYTES                          28
#define HAM_FRAME_COUNT                          256
#define HAM_LIVE_ROWS                            2
#define HAM_TEMPORAL_START_ROW                   2
#define HAM_TEMPORAL_ROWS                        16
#define HAM_TEMPORAL_HALF_ROWS                   8
#define HAM_HALFRATE_START_ROW                   18
#define HAM_DYNAMIC_ROWS                         18
#define HAM_DYNAMIC_PLANE_BYTES                  504
#define HAM_DYNAMIC_BITMAP_BYTES                 2016
#define HAM_HALFRATE_ROWS                        34
#define HAM_HALFRATE_FRAME_COUNT                 128
#define HAM_HALFRATE_ROW_CACHE_PLANE_BYTES       952
#define HAM_HALFRATE_ROW_CACHE_FRAME_BYTES       3808
#define HAM_HALFRATE_ROW_CACHE_BYTES             487424
#define HAM_DYNAMIC_BUFFER_BYTES                 4032
#define HAM_TEMPORAL_UPPER_DEST_OFFSET           56
#define HAM_TEMPORAL_LOWER_DEST_OFFSET           280
#define HAM_COPPER_BPLPTR_WORD                   23
#define HAM_COPPER_HALFRATE_BPLPTR_WORD          277
#define HAM_COPPER_HALFRATE_BPLPTR_BYTES         554
#define HAM_COPPER_WORDS                         692
#define HAM_COPPER_BYTES                         1384
#define HAM_CHIP_BLOCK_BYTES                     6800
#define HAM_TOTAL_CHIP_BYTES                     494224
#define HAM_HALF_COLUMNS                         28
#define HAM_HALF_ROWS                            26
#define HAM_SCREEN_WIDTH                         320
#define HAM_SCREEN_HEIGHT                        256
#define HAM_START_X                              48
#define HAM_PAL_VPOS_TOP                         0x002C
#define HAM_VPOS_START                           0x0044
#define HAM_VPOS_STOP                            0x0114
#define HAM_DIWSTRT                              0x4481
#define HAM_DIWSTOP                              0x14C1
#define HAM_DDF_SHIFT_BYTES                      6
#define HAM_DDFSTRT                              0x0050
#define HAM_DDFSTOP                              0x00B8
#define HAM_REPEAT_MOD                           0xFFE4
#define HAM_ADVANCE_MOD                          0
#define HAM_DISPLAY_BPU                          7
#define HAM_CONTROL_WORD_P5                      0x3333
#define HAM_CONTROL_WORD_P6                      0x6666
#define HAM_CORE_DONE_LOW                        0x4C
#define HAM_TEMPORAL_UPPER_DONE_LOW              0x6C
#define HAM_TEMPORAL_DONE_LOW                    0x8C
#define HAM_ZOOM_BASE                            256
#define HAM_ZOOM_AMPLITUDE                       96
#define HAM_ANGLE_PHASE_STEP                     1
#define HAM_CENTER_U                             0x4000
#define HAM_CENTER_V                             0x4000
#define BLTPRI_SET                               0x8400
#define BLTPRI_CLR                               0x0400
#define BLIT_TEMPORAL_WIDE_SIZE                  0x0100
#define BLIT_TEMPORAL_TAIL_SIZE                  0x0130
#define BLIT_TEMPORAL_WIDE_BYTES                 128
#define BLIT_TEMPORAL_TAIL_BYTES                 96
#define BLIT_TEMPORAL_WIDE_MOD_LONG              0x01780178
#define BLIT_TEMPORAL_TAIL_MOD_LONG              0x01980198
